### ISSUE TITLE
rime

### ISSUE THREAD

**Issue by s5unty** [s5unty/dotfiles#2]
启用调频 `enable_user_dict` :tada: 

禁用单码字调频、双码字调频 [goto](https://github.com/rime/squirrel/issues/97)

```yml
  disable_user_dict_for_patterns:
    - "^[a-z;,./]$"           # 禁止单码字调频
    - "^[a-z;,./][a-z;,./]$"  # 禁止双码字调频
```

删除自造词: 选中自造词所在的候选项，**Ctrl-Delete**

创建自造词: 活用分词符 `delimiter`

```yml
speller:
  alphabet: 'abcdefghijklmnopqrstuvwxyz;,./'
  initials: 'abcdefghijklmnopqrstuvwxyz'
  delimiter: "`':"
```

例如自造词 3 字的人名「陈世美」

```text
1. cm;`sjb`mi
陈世美
2. cmsm
陈世美
```
